apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: grafana-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: grafana-cluster-role
  apiGroup: rbac.authorization.k8s.io
